### ISSUE TITLE
How to use Images inside the Blog of MDX format 

### ISSUE THREAD

**Issue by Shailendra1703** [dillionverma/portfolio#12]
I tried using the mdx format but it didn't worked for me 

`![alttext](image path)`

can any one suggest how can I use images inside a blog post ?

**Comment by pyerino** [comment]
It works for me. Can you send the code you're using, please?

**Comment by Shailendra1703** [comment]
> It works for me. Can you send the code you're using, please?

---
title: "My Blog"
publishedAt: "2024-07-18"
summary: "My first post on my new blog."
---

I'm simply importing my image from the public folder with the below syntax.

`![myimage](/public/images/myblog.jp)`

```jsx
console.log("Hello World");
```

**Comment by pyerino** [comment]
I think your problem is with directory. 

Try removing `/public`:

# Old
`![myimage](/public/images/myblog.jp)`

# New one
`![myimage](/images/myblog.jp)`
